export const ROUTES = {
  HOME: '/',
  SEARCH: '/search',
  BOOK: '/book-detail',
  SIGNUP: '/signup',
  LOGIN: '/login',
  AUTH_VERIFY_EMAIL: '/auth/verify-email',
  AUTH_SEND_EMAIL: '/auth/send-email',
  BOOK_REGISTER: '/book-detail/book-register',
  BOOK_EDIT: '/book-detail/edit',
  LIBRARY: '/my-bookshelf',
  FAVORITES: '/favorites',
  PROFILE: '/profile',
  CHAT: '/chat',
};
